<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-11-16T16:40:19 ICT" name="Suite" finished-at="2023-11-16T16:41:17 ICT" duration-ms="57405">
    <groups>
    </groups>
    <test started-at="2023-11-16T16:40:19 ICT" name="Test" finished-at="2023-11-16T16:41:17 ICT" duration-ms="57405">
      <class name="com.seatech.test.login.LoginTestcase">
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:com.seatech.test.login.LoginTestcase@672b72ba]" started-at="2023-11-16T16:40:19 ICT" name="beforeTest" finished-at="2023-11-16T16:40:23 ICT" duration-ms="3554" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.seatech.test.login.LoginTestcase@672b72ba]" started-at="2023-11-16T16:40:23 ICT" name="setUp" finished-at="2023-11-16T16:40:23 ICT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="LoginTestcase()[pri:0, instance:com.seatech.test.login.LoginTestcase@672b72ba]" started-at="2023-11-16T16:40:23 ICT" name="LoginTestcase" description="Login - Verify Login" finished-at="2023-11-16T16:40:41 ICT" duration-ms="18356" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.seatech.test.login.LoginTestcase.LoginTestcase(LoginTestcase.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTestcase -->
        <test-method signature="DashboardTestcase()[pri:1, instance:com.seatech.test.login.LoginTestcase@672b72ba]" started-at="2023-11-16T16:40:41 ICT" name="DashboardTestcase" description="Click choose sub menu" finished-at="2023-11-16T16:40:47 ICT" duration-ms="5205" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DashboardTestcase -->
        <test-method signature="verifyTitle()[pri:2, instance:com.seatech.test.login.LoginTestcase@672b72ba]" started-at="2023-11-16T16:40:47 ICT" name="verifyTitle" description="Verify Title" finished-at="2023-11-16T16:41:17 ICT" duration-ms="30048" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTitle -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.seatech.test.login.LoginTestcase@672b72ba]" started-at="2023-11-16T16:41:17 ICT" name="tearDown" finished-at="2023-11-16T16:41:17 ICT" duration-ms="131" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.seatech.test.login.LoginTestcase -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
